config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  devise_for :users

  resources :experiences
  resources :skills
  resources :requests do
    resources :offers, only: [:create, :destroy]
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get '/login', to: 'sessions#new', as: 'login'
  # delete '/logout', to: 'sessions#destroy', as: 'logout'
  #
  # get 'myprofile', to: 'profile#show', as: :show_profile
  # get 'profile', to: 'profile#edit', as: :edit_profile
  # patch 'profile', to: 'profile#update'

  get '/requests', to: "requests#index"
  get '/skills', to: "skills#index"

  get 'home/index'
  # get 'sign_up', to: 'registration#new'
  # post 'sign_up', to: 'registration#create'

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  namespace :api, default: {format: 'json'} do
    get 'requests/search', to: 'requests#search'
    get 'offers/search', to: 'offers#search'
    get 'skills/search', to: 'skills#search'
    get 'addresses/search', to: 'addresses#search'

    # root 'home#index'
    # get 'auth', to: 'home#auth'

    resources :requests, :offers, :skills, :experiences, :addresses, :users
    # get '/users', to: 'users#index'
    # post '/users/create', to: 'users#create'

    #devise_for :users

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :request
  has_one :offer_detail, dependent: :destroy
  # accepts_nested_attributes_for :offer_detail
end

app/models/offer_detail.rb
class OfferDetail < ApplicationRecord
  belongs_to :offer
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :offers, dependent: :destroy
  has_many :proposals, dependent: :destroy, through: :offers, source: :offer_detail

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_address, dependent: :destroy
  has_many :offers, dependent: :delete_all
  has_many :experiences, dependent: :delete_all
  has_and_belongs_to_many :skills
  has_many :proposals, through: :offers, source: :offer_detail

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
  validates :first_name, presence: {message: "First name is required"}

  alias_method :authenticate, :valid_password?

  def self.from_token_payload(payload)
    self.find payload["sub"]
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  include Knock::Authenticable
  undef_method :current_user

  protect_from_forgery with: :null_session

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_user_logged_in!
  before_action :get_selected_request, only: [:create, :destroy]

  # def create
  #   byebug
  #   @offer = @request.offers.new(offer_params)
  #   @offer.user_id = Current.user.id
  #   if @offer.save
  #     redirect_to @request, notice: "Offer successfully added"
  #   else
  #     redirect_to @request, alert: "Something went wrong!"
  #   end
  # end
  #

  def create
    offer_detail_params = offer_params.delete(:offer_detail)
    @offer = @request.offers.new(offer_params)
    @offer.user_id = Current.user.id
    if @offer.save
      if offer_detail_params.present?
        offer_detail = OfferDetail.new(offer_detail_params)
        offer_detail.offer = @offer
        offer_detail.save
      end
      redirect_to @request, notice: "Offer successfully added"
    else
      redirect_to @request, alert: "Something went wrong!"
    end
  end

  def destroy
    @offer = @request.offers.find(params[:id])
    @offer.destroy
    redirect_to @request, notice: "Offer deleted"
  end

  private

  def get_selected_request
    @request = Request.find(params[:request_id])
  end

  def offer_params
    #params.require(:offer).permit(:value, :days, :description)
    params.require(:offer).permit!
    #params.require(:offer).permit(:value, offer_detail_attributes: [:days, :description])
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardeners</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>


<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to "GARDENERS", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Requests", requests_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Skills", skills_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Experience", experiences_path, class: "nav-link" %>
        </li>
        <% end %>
    </ul>

    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary"  %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
    </ul>

  </div>
</nav>