config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  devise_for :users

  resources :experiences
  resources :skills
  resources :requests do
    resources :offers, only: [:create, :destroy]
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get '/login', to: 'sessions#new', as: 'login'
  # delete '/logout', to: 'sessions#destroy', as: 'logout'
  #
  # get 'myprofile', to: 'profile#show', as: :show_profile
  # get 'profile', to: 'profile#edit', as: :edit_profile
  # patch 'profile', to: 'profile#update'

  get '/requests', to: "requests#index"
  get '/skills', to: "skills#index"

  get 'home/index'
  # get 'sign_up', to: 'registration#new'
  # post 'sign_up', to: 'registration#create'

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  namespace :api, default: {format: 'json'} do
    get 'requests/search', to: 'requests#search'
    get 'offers/search', to: 'offers#search'
    get 'skills/search', to: 'skills#search'
    get 'addresses/search', to: 'addresses#search'

    # root 'home#index'
    # get 'auth', to: 'home#auth'

    resources :requests, :offers, :skills, :experiences, :addresses, :users
    # get '/users', to: 'users#index'
    # post '/users/create', to: 'users#create'

    #devise_for :users

  end
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :offers, dependent: :destroy
  has_many :proposals, dependent: :destroy, through: :offers, source: :offer_detail

end

app/controllers/api/requests_controller.rb
class Api::RequestsController < ApiController
  before_action :authenticate_user

  def index
    render json: Request.all, include: :offers
  end

  def show
    request = Request.find_by(id: params[:id])
    if request
      render json: request, include: :offers
    else
      render json: {error: 'Request not found'}, status: 404
    end
  end

  def search
    if params[:subject]
      render json: Request.where('subject LIKE ?', "%#{params[:subject]}%"), include: :offers
      else if params[:desc]
             render json: Request.where('description LIKE ?', "%#{params[:desc]}%"), include: :offers
           else
             render json: {error: 'Request not found, search query missing'}, status: 404
           end
    end
  end

  def create
    request = Request.new(subject: params[:subject], description: params[:desc])
    if request.save
      render json: request
    else
      render json: {error: 'Cannot create request'}, status: 404
    end
  end

  def destroy
    request = Request.find_by(id: params[:id])
    if request.destroy
      render json: {message: 'request deleted'}, status: :ok
    else
      render json: {error: 'Cannot delete request'}, status: :unprocessable_entity
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:subject, :description)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label"><%= form.label :subject %></label>
    <div class="col-sm-10">
      <%= form.text_field :subject, class: "form-control"%>
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label"><%= form.label :description %></label>
    <div class="col-sm-10">
      <%= form.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<div class="mb-1"></div>
<%= link_to 'Show', @request, class: "btn btn-success" %> |
<%= link_to 'Back', requests_path, class: "btn btn-secondary" %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr scope="row">
        <td><%= request.subject %></td>
        <td><%= request.description %></td>
        <td><%= link_to 'Show', request, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_request_path(request), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path, class: "btn btn-primary"  %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>
<div class="mb-2"></div>
<%= link_to 'Back', requests_path, class: "btn btn-secondary" %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card text-center">
  <div class="card-header">
    Subject:
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= @request.subject %></h5>
    <p class="card-text"><%= @request.description %></p>
    <%= link_to 'Edit', edit_request_path(@request) , class: "btn btn-primary" %>

    <%= link_to 'Back', requests_path, class: "btn btn-secondary" %>

  </div>

</div>
<div class="card-footer text-muted">
  <%= form_for ([@request, @request.offers.new]) do |f| %>
    Value: <%= f.text_field :value , class: "form-control" %><br />
    <%= f.fields_for :offer_detail do |od| %>
      Days: <%= od.text_field :days , class: "form-control" %>
      Description: <%= od.text_field :description, class: "form-control mb-3"  %>

    <% end %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

<%= render @request.offers.where(user: Current.user) %>