config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  devise_for :users

  resources :experiences
  resources :skills
  resources :requests do
    resources :offers, only: [:create, :destroy]
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get '/login', to: 'sessions#new', as: 'login'
  # delete '/logout', to: 'sessions#destroy', as: 'logout'
  #
  # get 'myprofile', to: 'profile#show', as: :show_profile
  # get 'profile', to: 'profile#edit', as: :edit_profile
  # patch 'profile', to: 'profile#update'

  get '/requests', to: "requests#index"
  get '/skills', to: "skills#index"

  get 'home/index'
  # get 'sign_up', to: 'registration#new'
  # post 'sign_up', to: 'registration#create'

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  namespace :api, default: {format: 'json'} do
    get 'requests/search', to: 'requests#search'
    get 'offers/search', to: 'offers#search'
    get 'skills/search', to: 'skills#search'
    get 'addresses/search', to: 'addresses#search'

    # root 'home#index'
    # get 'auth', to: 'home#auth'

    resources :requests, :offers, :skills, :experiences, :addresses, :users
    # get '/users', to: 'users#index'
    # post '/users/create', to: 'users#create'

    #devise_for :users

  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
end

app/controllers/api/experiences_controller.rb
class Api::ExperiencesController < ApiController
  before_action :authenticate_user

  def index
    render json: Experience.all
  end

  def show
    # returns certain user experience
    experiences = Experience.where("user_id =#{params[:id]}")
    if experiences
      render json: experiences
    else
      render json: {error: 'No experiences found'}, status: 404
    end
  end

  def create
    user = User.find(params[:id])
    experience = user.experiences.new(project_name: params[:project], from: params[:from], to: params[:to] , description: params[:desc])
    if experience.save
      render json: experience
    else
      render json: {error: 'Cannot create experience'}, status: 404
    end
  end


end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_experience , only: %i[ show edit update destroy ]

  # GET /experiences or /experiences.json
  def index
    @experiences = Current.user.experiences.all
  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences or /experiences.json
  def create

    @experience = Experience.new(experience_params)
    @experience.user = Current.user
    #byebug
    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:project_name, :from, :to, :description, :user)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :user, Current.user %>

  <div class="form-group row">
    <%= form.label :project_name %>
    <%= form.text_field :project_name , class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :from %>
    <%= form.date_select :from  , class: "form-control"%>
  </div>

  <div class="form-group row">
    <%= form.label :to %>
    <%= form.date_select :to , class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Show', @experience, class: "btn btn-success" %> |
<%= link_to 'Back', experiences_path ,class: "btn btn-secondary" %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Project name</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr  scope="row">
        <td><%= experience.project_name %></td>
        <td><%= experience.from %></td>
        <td><%= experience.to %></td>
        <td><%= experience.description %></td>
        <td><%= link_to 'Show', experience , class: "btn btn-success"%></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) , class: "btn btn-primary"%></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path , class: "btn btn-primary" %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Back', experiences_path, class: "btn btn-secondary" %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @experience.project_name %>
</p>

<p>
  <strong>From:</strong>
  <%= @experience.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @experience.to %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experience.description %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) , class: "btn btn-primary"%> |
<%= link_to 'Back', experiences_path, class: "btn btn-secondary" %>